In [91]:
pip install matplotlib pandas numpy

Requirement already satisfied: matplotlib in d:\llm_code_assistant\.venv\lib\site-packages (3.10.1)
Requirement already satisfied: pandas in d:\llm_code_assistant\.venv\lib\site-packages (2.2.3)
Requirement already satisfied: numpy in d:\llm_code_assistant\.venv\lib\site-packages (2.2.2)
Requirement already satisfied: contourpy>=1.0.1 in d:\llm_code_assistant\.venv\lib\site-packages (from matplotlib) (1.3.1)
Requirement already satisfied: cycler>=0.10 in d:\llm_code_assistant\.venv\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in d:\llm_code_assistant\.venv\lib\site-packages (from matplotlib) (4.56.0)
Requirement already satisfied: kiwisolver>=1.3.1 in d:\llm_code_assistant\.venv\lib\site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: packaging>=20.0 in d:\llm_code_assistant\.venv\lib\site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in d:\llm_code_assistant\.venv\lib\site-packages (from matplotlib) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in d:\llm_code_assistant\.venv\lib\site-packages (from matplotlib) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in d:\llm_code_assistant\.venv\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in d:\llm_code_assistant\.venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in d:\llm_code_assistant\.venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in d:\llm_code_assistant\.venv\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [92]:
from matplotlib import pyplot as plt
import pandas as pd
import numpy as np
import re
import os

In [9]:
with open('logs\specification.txt', 'r') as f:
    lines = f.readlines()

data = [re.findall(r'\d+', line) for line in lines]
df = pd.DataFrame(data, columns=["Unambiguity", "Understandability", "Correctness", "Verifiability"])
df = df.astype(int)
df

<>:1: SyntaxWarning: invalid escape sequence '\s'
<>:1: SyntaxWarning: invalid escape sequence '\s'
C:\Users\hunat\AppData\Local\Temp\ipykernel_956\4061477662.py:1: SyntaxWarning: invalid escape sequence '\s'
  with open('logs\specification.txt', 'r') as f:

    Unambiguity  Understandability  Correctness  Verifiability
0             5                  5            5              5
1             5                  5            5              5
2             5                  5            5              5
3             5                  5            5              5
4             5                  5            5              5
5             4                  5            5              4
6             5                  5            5              5
7             5                  5            5              5
8             5                  5            5              5
9             4                  5            5              4
10            5                  5            5              5
11            5                  5            5              5
12            4                  5            5              4
13            5                  5            5              5
14            4                  5            5              4
15            5                  5            5              5
16            4                  5            5              4
17            5                  5            5              5
18            4                  5            5              4
19            5                  5            5              5
20            4                  5            5              4
21            5                  5            5              5
22            5                  5            5              5
23            4                  5            5              4
24            5                  5            5              5
25            4                  5            5              4
26            5                  5            5              5
27            5                  5            5              5
28            5                  5            5              5
29            4                  5            5              4
30            5                  5            5              5
31            5                  5            5              5
32            4                  5            5              4
33            5                  5            5              5
34            5                  5            5              5
35            4                  5            5              4
36            5                  5            5              5
37            5                  5            5              5
38            4                  5            5              4
39            5                  5            5              5
40            4                  5            5              4
41            5                  5            5              5
42            5                  5            5              5
43            4                  5            5              4
44            5                  5            5              5

In [10]:
df.describe()

       Unambiguity  Understandability  Correctness  Verifiability
count    45.000000               45.0         45.0      45.000000
mean      4.666667                5.0          5.0       4.666667
std       0.476731                0.0          0.0       0.476731
min       4.000000                5.0          5.0       4.000000
25%       4.000000                5.0          5.0       4.000000
50%       5.000000                5.0          5.0       5.000000
75%       5.000000                5.0          5.0       5.000000
max       5.000000                5.0          5.0       5.000000

In [11]:
count = (df < 5).any(axis=1).sum()
print(count)

15

In [14]:
df.to_csv('logs\specification_eval.csv', index=False)

<>:1: SyntaxWarning: invalid escape sequence '\s'
<>:1: SyntaxWarning: invalid escape sequence '\s'
C:\Users\hunat\AppData\Local\Temp\ipykernel_956\4037218730.py:1: SyntaxWarning: invalid escape sequence '\s'
  df.to_csv('logs\specification_eval.csv', index=False)

In [18]:
generation_path = 'logs\\generation'
generation_logs = os.listdir(generation_path)
print(generation_logs)

['.ipynb_checkpoints', 'Apple_relocate.txt', 'Apple___init__.txt', 'Game_end_game.txt', 'Game_exit_game.txt', 'Game_start_game.txt', 'Game___init__.txt', 'Snake_change_direction.txt', 'Snake_check_collision.txt', 'Snake_grow.txt', 'Snake_move.txt', 'Snake___init__.txt', 'UserInterface_handle_input.txt', 'UserInterface_render.txt']

In [71]:
code_generation = {}
code_generation['gpt-4o'] = {'attempts': [], 'error': []}
code_generation['claude3-7-sonnet'] = {'attempts': [], 'error': []}
print(code_generation)

{'gpt-4o': {'attempts': [], 'error': []}, 'claude3-7-sonnet': {'attempts': [], 'error': []}}

In [72]:
for log in generation_logs[1:]:
    log_path = f'logs\\generation\\{log}'
    with open(log_path, 'r') as log_file:
        lines = log_file.readlines()
        for line in lines:
            line_values = line.split(' ')
            if line_values[0] == 'gpt-4o':
                code_generation['gpt-4o']['attempts'].append(int(line_values[1]))
                code_generation['gpt-4o']['error'].append(int(line_values[2].rstrip()))
            else:
                code_generation['claude3-7-sonnet']['attempts'].append(int(line_values[1]))
                code_generation['claude3-7-sonnet']['error'].append(int(line_values[2].rstrip()))

In [68]:
code_generation

{'gpt-4o': {'attempts': [], 'error': []},
 'claude3-7-sonnet': {'attempts': [], 'error': []}}

In [83]:
gpt_attempts = []
gpt_errors = []
claude_attempts = []
claude_errors = []
for llm in code_generation.keys():
    for attempts, error in zip(code_generation[llm]['attempts'], code_generation[llm]['error']):
        if llm == 'gpt-4o':
            gpt_attempts.append(attempts)
            gpt_errors.append(error)
        else:
            claude_attempts.append(attempts)
            claude_errors.append(error)

In [84]:
print(gpt_attempts)
print(gpt_errors)
print(claude_attempts)
print(claude_errors)

[1, 2, 2, 5, 2, 2, 2, 4, 3, 2, 2, 3, 1]
[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[5, 3, 1, 2, 5, 5, 5, 5, 5, 5, 4, 5, 1]
[1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0]

In [80]:
def create_dict(values_list, facts_list):
    result_dict = {}
    for value in values_list:
        result_dict[value] = facts_list.count(value)
    return result_dict

In [85]:
gpt_attempts = create_dict([1,2,3,4,5], gpt_attempts)
gpt_errors = create_dict([0,1], gpt_errors)
claude_attempts = create_dict([1,2,3,4,5], claude_attempts)
claude_errors = create_dict([0,1], claude_errors)

In [86]:
print(gpt_attempts)
print(gpt_errors)
print(claude_attempts)
print(claude_errors)

{1: 2, 2: 7, 3: 2, 4: 1, 5: 1}
{0: 12, 1: 1}
{1: 2, 2: 1, 3: 1, 4: 1, 5: 8}
{0: 5, 1: 8}

In [90]:
x = np.array(list(gpt_attempts.keys()))
y1 = list(gpt_attempts.values())
y2 = list(claude_attempts.values())

# Set the width of the bars
bar_width = 0.4

# X-axis positions for each dataset
x1_positions = x - bar_width / 2
x2_positions = x + bar_width / 2

# Create the bar chart
plt.figure(figsize=(8, 5))
plt.bar(x1_positions, y1, width=bar_width, color='blue', label='GPT-4o', alpha=0.7)
plt.bar(x2_positions, y2, width=bar_width, color='red', label='Claude 3.7 Sonnet', alpha=0.7)

# Labels and title
plt.xlabel("Attempts")
plt.ylabel("Frequency")
plt.title("LLM Agents Attempt Frequency During Function Implementation")
plt.xticks(x)  # Ensure x-axis labels align with bars
plt.legend()

# Show the plot
plt.show()

NameError: name 'np' is not defined